# Generated by Django 5.2.16 on 2026-08-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='service_area',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='service_area',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='service_area',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='preferred_language',
        ),
        migrations.AddField(
            model_name='caregiver',
            name='house_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='panchayath',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='pincode',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='place',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='ward_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='doctor',
            name='house_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='panchayath',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='pincode',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='place',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='ward_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='nurse',
            name='house_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='nurse',
            name='panchayath',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='nurse',
            name='pincode',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='nurse',
            name='place',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='nurse',
            name='ward_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='house_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='panchayath',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='pincode',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='place',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='ward_no',
            field=models.IntegerField(default=1),
        ),
    ]
