# Generated by Django 5.2.16 on 2026-08-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_caregiver_latitude_remove_caregiver_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='discharge_summary_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
