# Generated by Django 5.2.16 on 2026-08-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patient_discharge_summary_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='service_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='service_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
