# Generated by Django 5.2.16 on 2026-08-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctor_service_area_nurse_service_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='house_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='panchayath',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='place',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='ward_no',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='house_name',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='panchayath',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='place',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='ward_no',
        ),
        migrations.AddField(
            model_name='administrator',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administrator',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='administrator',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='administrator',
            name='qualification',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='qualification',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
