# Generated by Django 5.2.16 on 2026-08-27 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_doctor_house_name_remove_doctor_panchayath_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRegistrationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('password_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('house_name', models.CharField(default='N/A', max_length=50)),
                ('place', models.CharField(default='N/A', max_length=50)),
                ('panchayath', models.CharField(default='N/A', max_length=50)),
                ('ward_no', models.IntegerField(default=1)),
                ('pincode', models.CharField(default='N/A', max_length=50)),
                ('discharge_summary_path', models.CharField(max_length=255)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('registration_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_applications', to='accounts.patient')),
                ('reviewed_by_doctor', models.ForeignKey(blank=True, db_column='reviewed_by_doctor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor')),
            ],
            options={
                'db_table': 'patient_registration_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
