# Generated by Django 5.2.16 on 2026-10-05 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='experience_years',
            field=models.CharField(blank=True, default='1+ years', max_length=50),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='verified_by_nurse',
            field=models.ForeignKey(blank=True, db_column='verified_by_nurse_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.nurse'),
        ),
    ]
