# Generated by Django 5.2.16 on 2026-08-05 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed')], default='Pending', max_length=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lab_reports', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_lab_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_reports',
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'db_table': 'medical_documents',
            },
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('dietary_recommendations', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Superseded', 'Superseded')], default='Active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'db_table': 'nutrition_plans',
            },
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('allergy_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergy_name', models.CharField(max_length=100)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'db_table': 'patient_allergies',
            },
        ),
        migrations.CreateModel(
            name='PatientChronicCondition',
            fields=[
                ('condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'db_table': 'patient_chronic_conditions',
            },
        ),
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis_text', models.TextField()),
                ('diagnosed_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'db_table': 'patient_diagnosis',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Superseded', 'Superseded')], default='Active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('change_type', models.CharField(choices=[('New', 'New'), ('Continued', 'Continued'), ('Discontinued', 'Discontinued'), ('DosageChanged', 'DosageChanged')], max_length=15)),
                ('prescription', models.ForeignKey(db_column='prescription_id', on_delete=django.db.models.deletion.CASCADE, to='medical_records.prescription')),
            ],
            options={
                'db_table': 'prescription_items',
            },
        ),
    ]
