# Generated by Django 5.2.16 on 2026-08-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='investigation_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
