# Generated by Django 5.2.16 on 2026-08-05 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverPatientAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Ended', 'Ended')], default='Active', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by_nurse', models.ForeignKey(db_column='assigned_by_nurse_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.nurse')),
                ('caregiver', models.ForeignKey(db_column='caregiver_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.caregiver')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'db_table': 'caregiver_patient_assignment',
            },
        ),
        migrations.CreateModel(
            name='HomeVisitSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('TwiceWeekly', 'TwiceWeekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly')], max_length=20)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Modified', 'Modified'), ('Ended', 'Ended')], default='Active', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'db_table': 'home_visit_schedules',
            },
        ),
        migrations.CreateModel(
            name='HomeVisitOccurrence',
            fields=[
                ('occurrence_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('visit_type', models.CharField(choices=[('Recurring', 'Recurring'), ('Additional', 'Additional')], max_length=15)),
                ('urgency_level', models.CharField(blank=True, choices=[('Routine', 'Routine'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], max_length=15, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Skipped', 'Skipped'), ('Rescheduled', 'Rescheduled')], default='Scheduled', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_nurse', models.ForeignKey(blank=True, db_column='allocated_nurse_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_occurrences', to='accounts.nurse')),
                ('approved_by_nurse', models.ForeignKey(blank=True, db_column='approved_by_nurse_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_occurrences', to='accounts.nurse')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('requested_by', models.ForeignKey(blank=True, db_column='requested_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, db_column='schedule_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='care_coordination.homevisitschedule')),
            ],
            options={
                'db_table': 'home_visit_occurrences',
            },
        ),
        migrations.CreateModel(
            name='HomeVisitSummary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_pressure', models.CharField(blank=True, max_length=15, null=True)),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('oxygen_level', models.IntegerField(blank=True, null=True)),
                ('treatment_notes', models.TextField(blank=True, null=True)),
                ('next_visit_recommendation', models.DateField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nurse', models.ForeignKey(db_column='nurse_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.nurse')),
                ('occurrence', models.OneToOneField(db_column='occurrence_id', on_delete=django.db.models.deletion.CASCADE, to='care_coordination.homevisitoccurrence')),
            ],
            options={
                'db_table': 'home_visit_summaries',
            },
        ),
        migrations.CreateModel(
            name='TelemedicineConsultation',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_datetime', models.DateTimeField(auto_now_add=True)),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rescheduled', 'Rescheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=20)),
                ('meeting_link', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('requested_by', models.ForeignKey(db_column='requested_by_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telemedicine_consultations',
            },
        ),
        migrations.CreateModel(
            name='VisitSymptom',
            fields=[
                ('symptom_id', models.AutoField(primary_key=True, serialize=False)),
                ('symptom_name', models.CharField(max_length=100)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('summary', models.ForeignKey(db_column='summary_id', on_delete=django.db.models.deletion.CASCADE, to='care_coordination.homevisitsummary')),
            ],
            options={
                'db_table': 'visit_symptoms',
            },
        ),
    ]
