# Generated by Django 5.2.16 on 2026-09-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_coordination', '0003_home_visit_team_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='homevisitoccurrence',
            name='is_doctor_customized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homevisitschedule',
            name='custom_days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='homevisitschedule',
            name='frequency',
            field=models.CharField(choices=[('Every Day', 'Every Day'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('TwiceWeekly', 'TwiceWeekly'), ('Every 2 Weeks', 'Every 2 Weeks'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Custom', 'Custom')], max_length=30),
        ),
    ]
