# Generated by Django 5.2.16 on 2026-10-05 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_caregiver_experience_years_caregiver_is_available_and_more'),
        ('care_coordination', '0004_homevisitoccurrence_is_doctor_customized_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caregiverpatientassignment',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.AddField(
            model_name='caregiverpatientassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caregiverpatientassignment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caregiverpatientassignment',
            name='assigned_by_nurse',
            field=models.ForeignKey(blank=True, db_column='assigned_by_nurse_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.nurse'),
        ),
        migrations.AlterField(
            model_name='caregiverpatientassignment',
            name='caregiver',
            field=models.ForeignKey(db_column='caregiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.caregiver'),
        ),
        migrations.AlterField(
            model_name='caregiverpatientassignment',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_assignments', to='accounts.patient'),
        ),
        migrations.AlterField(
            model_name='caregiverpatientassignment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Ended', 'Ended'), ('Terminated', 'Terminated')], default='Active', max_length=20),
        ),
        migrations.CreateModel(
            name='CaregiverComplaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Patient-related', 'Patient-related'), ('Schedule-related', 'Schedule-related'), ('Safety concern', 'Safety concern'), ('Payment / Administrative', 'Payment / Administrative'), ('Technical issue', 'Technical issue'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.TextField()),
                ('attachment_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Review', 'In Review'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(db_column='caregiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='accounts.caregiver')),
                ('resolved_by_nurse', models.ForeignKey(blank=True, db_column='resolved_by_nurse_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.nurse')),
            ],
            options={
                'db_table': 'caregiver_complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaregiverFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='care_coordination.caregiverpatientassignment')),
                ('caregiver', models.ForeignKey(db_column='caregiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='patient_feedbacks', to='accounts.caregiver')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_feedbacks', to='accounts.patient')),
            ],
            options={
                'db_table': 'caregiver_feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaregiverRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('patient_message', models.TextField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(db_column='caregiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='accounts.caregiver')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_requests', to='accounts.patient')),
            ],
            options={
                'db_table': 'caregiver_patient_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='caregiverpatientassignment',
            name='request',
            field=models.ForeignKey(blank=True, db_column='request_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='care_coordination.caregiverrequest'),
        ),
    ]
