# Generated by Django 5.2.16 on 2026-10-05 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_caregiver_experience_years_caregiver_is_available_and_more'),
        ('care_coordination', '0005_alter_caregiverpatientassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverpatientassignment',
            name='caregiver',
            field=models.ForeignKey(db_column='caregiver_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.caregiver'),
        ),
        migrations.AlterField(
            model_name='caregiverpatientassignment',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient'),
        ),
    ]
