# Generated by Django 5.2.16 on 2026-08-13 05:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctor_service_area_nurse_service_area'),
        ('care_coordination', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telemedicineconsultation',
            name='requested_datetime',
        ),
        migrations.RemoveField(
            model_name='telemedicineconsultation',
            name='scheduled_datetime',
        ),
        migrations.AddField(
            model_name='telemedicineconsultation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemedicineconsultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telemedicineconsultation',
            name='patient_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemedicineconsultation',
            name='priority',
            field=models.CharField(choices=[('Routine', 'Routine'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], default='Routine', max_length=15),
        ),
        migrations.AddField(
            model_name='telemedicineconsultation',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemedicineconsultation',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemedicineconsultation',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemedicineconsultation',
            name='requested_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemedicineconsultation',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemedicineconsultation',
            name='scheduled_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemedicineconsultation',
            name='scheduled_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemedicineconsultation',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled'), ('Requested', 'Requested'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TelemedicineConsultationNote',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('symptoms_discussed', models.TextField(blank=True, null=True)),
                ('clinical_observations', models.TextField(blank=True, null=True)),
                ('advice', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(db_column='consultation_id', on_delete=django.db.models.deletion.CASCADE, related_name='consultation_notes', to='care_coordination.telemedicineconsultation')),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'db_table': 'telemedicine_consultation_notes',
            },
        ),
        migrations.CreateModel(
            name='TelemedicineFollowUp',
            fields=[
                ('followup_id', models.AutoField(primary_key=True, serialize=False)),
                ('followup_date', models.DateField()),
                ('followup_time', models.TimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('followup_type', models.CharField(default='Telemedicine', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled'), ('Requested', 'Requested'), ('Approved', 'Approved')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('original_consultation', models.ForeignKey(db_column='original_consultation_id', on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='care_coordination.telemedicineconsultation')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'db_table': 'telemedicine_followups',
            },
        ),
    ]
