from django.urls import path
from care_coordination.views import DoctorHomeVisitsView
from care_coordination.caregiver_views import (
    NursePendingCaregiversView,
    NurseApproveCaregiverView,
    NurseRejectCaregiverView,
    NurseApprovedCaregiversView,
    NurseCaregiverComplaintsListView,
    NurseResolveCaregiverComplaintView,
    PatientApprovedCaregiversListView,
    PatientCaregiverStatusView,
    PatientCreateCaregiverRequestView,
    PatientSubmitCaregiverFeedbackView,
    CaregiverRequestsListView,
    CaregiverAcceptRequestView,
    CaregiverRejectRequestView,
    CaregiverActiveAssignmentView,
    CaregiverCompleteCareView,
    CaregiverCareHistoryView,
    CaregiverComplaintsView,
)
from .views import (
    RegisterView,
    CheckApplicationStatusView,
    LoginView,
    GoogleAuthView,
    ForgotPasswordRequestView,
    ForgotPasswordResendOtpView,
    ForgotPasswordVerifyOtpView,
    ForgotPasswordResetView,
    RefreshTokenView,
    LogoutView,
    SecureDocumentView,
    CurrentUserProfileView,
    DoctorPendingPatientsView,

    DoctorPatientDetailView,
    DoctorApprovePatientView,
    DoctorRejectPatientView,
    AdminPendingCaregiversView,
    AdminCaregiverDetailView,
    AdminApproveCaregiverView,
    AdminRejectCaregiverView,
    AdminCreateStaffView,
    AdminOnboardDoctorView,
    AdminOnboardNurseView,
    AdminApproveDoctorView,
    AdminRejectDoctorView,
    AdminApproveNurseView,
    AdminRejectNurseView,
    AdminStatsView,
    AdminProfileView,
    AdminUserListView,
    AdminUserToggleStatusView,
    AdminPatientListView,
    AdminActivityLogView,
    AdminWelfareSchemeListView,
    AdminWelfareSchemeDetailView,
    AdminEquipmentListView,
    AdminEquipmentTypeCreateView,
    AdminEquipmentUnitCreateView,
    AdminEquipmentUnitStatusUpdateView,
    AdminEquipmentAllocateView,
    AdminNotificationOverviewView,
    AdminReportsView,
    AdminAnalyticsView,
    PatientDashboardView,
    PatientProfileView,
    PatientMedicalHistoryView,
    PatientPrescriptionsView,
    PatientLabReportsView,
    PatientNutritionView,
    PatientHomeVisitsView,
    PatientEquipmentView,
    PatientWelfareView,
    PatientCaregiverView,
    PatientTimelineView,
    DoctorProfileView,
    DoctorDashboardView,
    DoctorAvailabilityView,
    DoctorPatientListView,
    DoctorPatientMedicalProfileView,
    DoctorPatientTimelineView,
    DoctorReportsView,
    NurseProfileView,
    NurseDashboardView,
    NurseAvailabilityView,
    NursePatientListView,
    NursePatientMedicalProfileView,
    NursePatientTimelineView,
    NurseReportsView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='auth_register'),
    path('auth/register/', RegisterView.as_view(), name='auth_register_prefixed'),
    path('application-status/', CheckApplicationStatusView.as_view(), name='auth_application_status'),
    path('auth/application-status/', CheckApplicationStatusView.as_view(), name='auth_application_status_prefixed'),
    path('login/', LoginView.as_view(), name='auth_login'),
    path('auth/login/', LoginView.as_view(), name='auth_login_prefixed'),
    path('google/', GoogleAuthView.as_view(), name='auth_google'),
    path('auth/google/', GoogleAuthView.as_view(), name='auth_google_prefixed'),
    path('forgot-password/request-otp/', ForgotPasswordRequestView.as_view(), name='forgot_password_request_otp'),
    path('auth/forgot-password/request-otp/', ForgotPasswordRequestView.as_view(), name='auth_forgot_password_request_otp'),
    path('forgot-password/resend-otp/', ForgotPasswordResendOtpView.as_view(), name='forgot_password_resend_otp'),
    path('auth/forgot-password/resend-otp/', ForgotPasswordResendOtpView.as_view(), name='auth_forgot_password_resend_otp'),
    path('forgot-password/verify-otp/', ForgotPasswordVerifyOtpView.as_view(), name='forgot_password_verify_otp'),
    path('auth/forgot-password/verify-otp/', ForgotPasswordVerifyOtpView.as_view(), name='auth_forgot_password_verify_otp'),
    path('forgot-password/reset/', ForgotPasswordResetView.as_view(), name='forgot_password_reset'),
    path('auth/forgot-password/reset/', ForgotPasswordResetView.as_view(), name='auth_forgot_password_reset'),
    path('token/refresh/', RefreshTokenView.as_view(), name='auth_token_refresh'),

    path('logout/', LogoutView.as_view(), name='auth_logout'),
    path('documents/view/', SecureDocumentView.as_view(), name='secure_document_view'),
    path('me/', CurrentUserProfileView.as_view(), name='auth_me'),

    # Nurse Portal Routes (Authenticated Nurse Only)
    path('nurse/profile/', NurseProfileView.as_view(), name='nurse_profile'),
    path('nurse/dashboard/', NurseDashboardView.as_view(), name='nurse_dashboard'),
    path('nurse/availability/', NurseAvailabilityView.as_view(), name='nurse_availability'),
    path('nurse/patients/', NursePatientListView.as_view(), name='nurse_patients'),
    path('nurse/patients/<int:patient_id>/profile/', NursePatientMedicalProfileView.as_view(), name='nurse_patient_medical_profile'),
    path('nurse/patients/<int:patient_id>/timeline/', NursePatientTimelineView.as_view(), name='nurse_patient_timeline'),
    path('nurse/reports/', NurseReportsView.as_view(), name='nurse_reports'),

    # Doctor Portal Routes (Authenticated Doctor Only)
    path('doctor/profile/', DoctorProfileView.as_view(), name='doctor_profile'),
    path('doctor/dashboard/', DoctorDashboardView.as_view(), name='doctor_dashboard'),
    path('doctor/availability/', DoctorAvailabilityView.as_view(), name='doctor_availability'),
    path('doctor/patients/', DoctorPatientListView.as_view(), name='doctor_patients'),
    path('doctor/patients/pending/', DoctorPendingPatientsView.as_view(), name='doctor_pending_patients'),
    path('doctor/patients/<int:patient_id>/', DoctorPatientDetailView.as_view(), name='doctor_patient_detail'),
    path('doctor/patients/<int:patient_id>/profile/', DoctorPatientMedicalProfileView.as_view(), name='doctor_patient_medical_profile'),
    path('doctor/patients/<int:patient_id>/timeline/', DoctorPatientTimelineView.as_view(), name='doctor_patient_timeline'),
    path('doctor/patients/<int:patient_id>/approve/', DoctorApprovePatientView.as_view(), name='doctor_approve_patient'),
    path('doctor/patients/<int:patient_id>/reject/', DoctorRejectPatientView.as_view(), name='doctor_reject_patient'),
    path('doctor/home-visits/', DoctorHomeVisitsView.as_view(), name='doctor_home_visits'),
    path('doctor/reports/', DoctorReportsView.as_view(), name='doctor_reports'),

    # Admin Caregiver Verification & Staff Creation routes
    path('admin/caregivers/pending/', AdminPendingCaregiversView.as_view(), name='admin_pending_caregivers'),
    path('admin/caregivers/<int:caregiver_id>/', AdminCaregiverDetailView.as_view(), name='admin_caregiver_detail'),
    path('admin/caregivers/<int:caregiver_id>/approve/', AdminApproveCaregiverView.as_view(), name='admin_approve_caregiver'),
    path('admin/caregivers/<int:caregiver_id>/reject/', AdminRejectCaregiverView.as_view(), name='admin_reject_caregiver'),
    path('admin/staff/create/', AdminCreateStaffView.as_view(), name='admin_create_staff'),
    path('admin/onboard-doctor/', AdminOnboardDoctorView.as_view(), name='admin_onboard_doctor'),
    path('admin/onboard-nurse/', AdminOnboardNurseView.as_view(), name='admin_onboard_nurse'),
    path('admin/doctors/<int:doctor_id>/approve/', AdminApproveDoctorView.as_view(), name='admin_approve_doctor'),
    path('admin/doctors/<int:doctor_id>/reject/', AdminRejectDoctorView.as_view(), name='admin_reject_doctor'),
    path('admin/nurses/<int:nurse_id>/approve/', AdminApproveNurseView.as_view(), name='admin_approve_nurse'),
    path('admin/nurses/<int:nurse_id>/reject/', AdminRejectNurseView.as_view(), name='admin_reject_nurse'),

    # Redesigned Phase 1 Administrator Dashboard & Management APIs
    path('admin/profile/', AdminProfileView.as_view(), name='admin_profile'),
    path('admin/stats/', AdminStatsView.as_view(), name='admin_stats'),
    path('admin/users/', AdminUserListView.as_view(), name='admin_users'),
    path('admin/users/<int:user_id>/toggle-status/', AdminUserToggleStatusView.as_view(), name='admin_user_toggle_status'),
    path('admin/patients/', AdminPatientListView.as_view(), name='admin_patients_readonly'),
    path('admin/activities/', AdminActivityLogView.as_view(), name='admin_activities'),
    path('admin/welfare-schemes/', AdminWelfareSchemeListView.as_view(), name='admin_welfare_schemes'),
    path('admin/welfare-schemes/<int:scheme_id>/', AdminWelfareSchemeDetailView.as_view(), name='admin_welfare_scheme_detail'),
    path('admin/equipment/', AdminEquipmentListView.as_view(), name='admin_equipment'),
    path('admin/equipment/types/', AdminEquipmentTypeCreateView.as_view(), name='admin_equipment_type_create'),
    path('admin/equipment/units/', AdminEquipmentUnitCreateView.as_view(), name='admin_equipment_unit_create'),
    path('admin/equipment/units/<int:unit_id>/status/', AdminEquipmentUnitStatusUpdateView.as_view(), name='admin_equipment_unit_status'),
    path('admin/equipment/requests/<int:request_id>/allocate/', AdminEquipmentAllocateView.as_view(), name='admin_equipment_allocate'),
    path('admin/notifications/', AdminNotificationOverviewView.as_view(), name='admin_notifications'),
    path('admin/reports/', AdminReportsView.as_view(), name='admin_reports'),
    path('admin/analytics/', AdminAnalyticsView.as_view(), name='admin_analytics'),

    # Official Phase 1 Patient Portal APIs (Authenticated Patient Only)
    path('patient/dashboard/', PatientDashboardView.as_view(), name='patient_dashboard'),
    path('patient/profile/', PatientProfileView.as_view(), name='patient_profile'),
    path('patient/medical-history/', PatientMedicalHistoryView.as_view(), name='patient_medical_history'),
    path('patient/prescriptions/', PatientPrescriptionsView.as_view(), name='patient_prescriptions'),
    path('patient/lab-reports/', PatientLabReportsView.as_view(), name='patient_lab_reports'),
    path('patient/nutrition/', PatientNutritionView.as_view(), name='patient_nutrition'),
    path('patient/home-visits/', PatientHomeVisitsView.as_view(), name='patient_home_visits'),
    path('patient/equipment/', PatientEquipmentView.as_view(), name='patient_equipment'),
    path('patient/welfare/', PatientWelfareView.as_view(), name='patient_welfare'),
    path('patient/caregiver/', PatientCaregiverStatusView.as_view(), name='patient_caregiver'),
    path('patient/timeline/', PatientTimelineView.as_view(), name='patient_timeline'),

    # Phase 1 Nurse Caregiver Management Routes
    path('nurse/caregivers/pending/', NursePendingCaregiversView.as_view(), name='accounts_nurse_pending_caregivers'),
    path('nurse/caregivers/<int:caregiver_id>/approve/', NurseApproveCaregiverView.as_view(), name='accounts_nurse_approve_caregiver'),
    path('nurse/caregivers/<int:caregiver_id>/reject/', NurseRejectCaregiverView.as_view(), name='accounts_nurse_reject_caregiver'),
    path('nurse/caregivers/approved/', NurseApprovedCaregiversView.as_view(), name='accounts_nurse_approved_caregivers'),
    path('nurse/caregiver-complaints/', NurseCaregiverComplaintsListView.as_view(), name='accounts_nurse_caregiver_complaints'),
    path('nurse/caregiver-complaints/<int:complaint_id>/resolve/', NurseResolveCaregiverComplaintView.as_view(), name='accounts_nurse_resolve_caregiver_complaint'),

    # Phase 1 Patient Caregiver Routes
    path('patient/caregivers/', PatientApprovedCaregiversListView.as_view(), name='accounts_patient_approved_caregivers'),
    path('patient/caregiver-requests/', PatientCreateCaregiverRequestView.as_view(), name='accounts_patient_create_caregiver_request'),
    path('patient/caregiver-feedback/', PatientSubmitCaregiverFeedbackView.as_view(), name='accounts_patient_submit_caregiver_feedback'),

    # Phase 1 Caregiver Portal Routes
    path('caregiver/requests/', CaregiverRequestsListView.as_view(), name='accounts_caregiver_requests_list'),
    path('caregiver/requests/<int:request_id>/accept/', CaregiverAcceptRequestView.as_view(), name='accounts_caregiver_accept_request'),
    path('caregiver/requests/<int:request_id>/reject/', CaregiverRejectRequestView.as_view(), name='accounts_caregiver_reject_request'),
    path('caregiver/assignment/', CaregiverActiveAssignmentView.as_view(), name='accounts_caregiver_active_assignment'),
    path('caregiver/assignment/complete/', CaregiverCompleteCareView.as_view(), name='accounts_caregiver_complete_care'),
    path('caregiver/assignment/<int:assignment_id>/complete/', CaregiverCompleteCareView.as_view(), name='accounts_caregiver_complete_care_id'),
    path('caregiver/care-history/', CaregiverCareHistoryView.as_view(), name='accounts_caregiver_care_history'),
    path('caregiver/complaints/', CaregiverComplaintsView.as_view(), name='accounts_caregiver_complaints'),
]

