# Generated by Django 5.2.16 on 2026-09-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welfarescheme',
            name='application_link',
        ),
        migrations.AddField(
            model_name='welfarescheme',
            name='application_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='welfarescheme',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='welfarescheme',
            name='category',
            field=models.CharField(default='Financial Aid', max_length=100),
        ),
        migrations.AddField(
            model_name='welfarescheme',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='welfarescheme',
            name='government_department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='welfarescheme',
            name='official_application_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='welfarescheme',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='welfarescheme',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Unpublished', 'Unpublished')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='welfarescheme',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='WelfareApplication',
        ),
    ]
