# Generated by Django 5.2.16 on 2026-08-05 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('equipment_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipment_types',
            },
        ),
        migrations.CreateModel(
            name='EquipmentUnit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Allocated', 'Allocated'), ('Maintenance', 'Maintenance'), ('Retired', 'Retired')], default='Available', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_type', models.ForeignKey(db_column='equipment_type_id', on_delete=django.db.models.deletion.CASCADE, to='resources.equipmenttype')),
            ],
            options={
                'db_table': 'equipment_units',
            },
        ),
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('delivery_status', models.CharField(choices=[('Requested', 'Requested'), ('Allocated', 'Allocated'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by_admin', models.ForeignKey(blank=True, db_column='allocated_by_admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.administrator')),
                ('approved_by_doctor', models.ForeignKey(blank=True, db_column='approved_by_doctor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('requested_by', models.ForeignKey(db_column='requested_by_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipment_type', models.ForeignKey(db_column='equipment_type_id', on_delete=django.db.models.deletion.CASCADE, to='resources.equipmenttype')),
                ('allocated_unit', models.ForeignKey(blank=True, db_column='allocated_unit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.equipmentunit')),
            ],
            options={
                'db_table': 'equipment_requests',
            },
        ),
        migrations.CreateModel(
            name='WelfareScheme',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, null=True)),
                ('required_documents', models.TextField(blank=True, null=True)),
                ('application_link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.ForeignKey(db_column='created_by_admin_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.administrator')),
            ],
            options={
                'db_table': 'welfare_schemes',
            },
        ),
        migrations.CreateModel(
            name='WelfareApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('UnderReview', 'UnderReview'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=20)),
                ('submitted_documents', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('reviewed_by_admin', models.ForeignKey(blank=True, db_column='reviewed_by_admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.administrator')),
                ('submitted_by', models.ForeignKey(db_column='submitted_by_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(db_column='scheme_id', on_delete=django.db.models.deletion.CASCADE, to='resources.welfarescheme')),
            ],
            options={
                'db_table': 'welfare_applications',
            },
        ),
    ]
